config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'index', to: 'todo_lists#index'

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sessions#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?

    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
       session[:user_id] = @user.id
       redirect_to '/index'
    else
       redirect_to '/welcome'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/welcome', notice: "Vous avez bien été déconnecté"
  end

  def welcome
  end

  def login
  end

  def page_required_login
  end



end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
     flash[:success] = "✅ La tâche a bien été supprimé de la To-Do Liste."
    else
     flash[:error] = "❌ La tâche n'a pas pu être supprimé de la To-Do Liste."
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "👏 La tâche est terminée !"
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  # GET /todo_lists or /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1 or /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists or /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_list_url(@todo_list), notice: "✅ La To-Do Liste a été créée." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_list_url(@todo_list), notice: "✅ La To-Do Liste a été éditée." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1 or /todo_lists/1.json
  def destroy
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy

    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: "✅ La To-Do Liste a été supprimée." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username,
      :password))
      session[:user_id] = @user.id
      redirect_to '/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

   # Logs in the given user.
   def log_in(user)
    session[:user_id] = user.id
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
 <% end %>

app/views/layouts/_todo_item.html.erb
<p><%= todo_item.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>TO-DAY</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>

    <%# Font %>

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <%# Bootstrap CSS %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <p>To-Do Liste App with Ruby on Rails</p>
      <a href="https://github.com/AurelianeD/Todo-List">👉 Github</a>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "Liste tes tâches afin de t'organiser plus facilement !" %>
  <%= f.submit "Ajouter"%>
 <% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <%if todo_item.completed_at? %>

    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>

    <div class="complete">

        <i style="opacity: 0.4;" class="fa fa-check"></i>
    </div>

    <div class="trash">
      <%= button_to "Supprimer la tâche", todo_list_todo_item_path(@todo_list, todo_item.id),
  method: :delete,
  data: { confirm: "Êtes-vous sur de vouloir supprimer cette tâche de la To Do List ?" } %>
    </div>

  <% else %>

    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>

    <div class="complete">
      <%= button_to complete_todo_list_todo_item_path(@todo_list, todo_item.id),
      method: :patch do %>
        <i class="fa fa-circle-thin"></i>
      <% end %>
    </div>

    <div class="trash">
      <%= button_to "Supprimer la tâche", todo_list_todo_item_path(@todo_list, todo_item.id),
  method: :delete,
  data: { confirm: "Êtes-vous sur de vouloir supprimer cette tâche de la To Do List ?" } %>
    </div>

  <% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="todo_list_sub_title">
    <%= form.label :Titre, style: "display: block" %>
    <%= form.text_field :title, placeholder: "Ex : Ruby on Rails App" %>
  </div>

  <div class="todo_list_sub_title">
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_area :description, placeholder: "Ex : Apprendre à coder une application web de gestion de To-Do listes avec Rails" %>
  </div>

  <div class="submit">
    <%= form.submit "Ajouter" %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">

  <h2 class="todo_list_title">
    <%= todo_list.title %>
  </h2>

  <p class="todo_list_sub_title">
    <%= todo_list.description %>
  </p>

</div>

app/views/todo_lists/edit.html.erb
<h1>Éditer <%= @todo_list.title %></h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div class="links">
  <%= link_to "Annuler les modifications", todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% if logged_in? %>
    <h1>👋 Hello <%= current_user.username %>!</h1>
<%end%>

<h1>🎯 Mes To-Do's</h1>

<% @todo_lists.each do |todo_list| %>

  <div class="index_row">
    <h2>▶️ <%= link_to todo_list.title, todo_list %></h2>
    <p><%= todo_list.description %></p>
  </div>

<% end %>

<div class="links">
  <%= link_to "✚ Ajouter une nouvelle To-Do liste", new_todo_list_path %>
  <%= button_to "Me déconnecter", logout_path, method: :delete %>
</div>

app/views/todo_lists/new.html.erb
<h1>📍 Nouvelle To-Do Liste</h1>

<%= render "form", todo_list: @todo_list %>

<br>

<div class="links">
  <%= link_to "◀️ Retour à l'accueil", todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<% flash.each do |type, msg| %>
  <div>
    <p id="notice"><%= msg %></p>
  </div>
<% end %>

<%= render @todo_list %>

<div id="todo_items_wrapper">
 <%= render @todo_list.todo_items %>
 <div id="form">
  <%= render "todo_items/form" %>
 </div>
</div>

<div class="links">

  <%= button_to "Supprimer cette To-Do liste", @todo_list, method: :delete,
  data: {confirm: "Supprimer cette to-do liste ?"} %>
  <%= link_to "Éditer cette To-Do liste", edit_todo_list_path(@todo_list) %> |

  <%= link_to "Retour à l'accueil", todo_lists_path %>

</div>

app/views/users/new.html.erb
<h1>📝 Je m'inscris</h1>

<%= form_for @user do |f|%>
  <div class="index_row">
    <%= f.label :username, "Pseudo"%><br>
    <%= f.text_field :username, placeholder: "Pseudo"%><br>
  </div>

  <div class="index_row">
    <%= f.label :password, "Mot de passe"%><br>
    <%= f.password_field :password, placeholder: "Mot de passe"%><br>
  </div>
  <div class="submit">
    <%= f.submit %>
  </div>
<%end%>

<div class="links">
  <%= link_to "◀️ Retour à l'accueil", welcome_path %>
</div>